-- Second rater: scores plus a one-line note. Notes were written in Chinese and
-- translated for display; the original is kept in note_original.
-- Appends only — it must not disturb the ratings already in the table.

insert into public.user_ratings (movie_idx, jumps, gore, dread, note, note_original, note_lang, source, user_id)
select v.movie_idx, v.jumps, v.gore, v.dread, v.note, v.note_original, v.note_lang, 'offline', null
from (values
  (56, 5, 4, 5, 'Handheld camera so shaky I felt sick. Screamed the whole way through. Never again.', '手持镜头晃到头晕全程尖叫不敢看第二遍', 'zh'),
  (118, 4, 4, 4, 'Zombies that RUN. My heart rate never came down.', '丧尸还会跑真的会心跳加速', 'zh'),
  (91, 2, 2, 2, 'Black-and-white art film. Less scary than just extremely cool.', '黑白文艺片与其说吓不如说很酷', 'zh'),
  (110, 5, 4, 3, 'Chased even in my sleep. Those finger blades did something to me.', '做梦都被追指甲刀太吓人', 'zh'),
  (42, 5, 3, 4, 'Held my breath along with them for the entire runtime.', '全程不敢出声跟着一起屏住呼吸', 'zh'),
  (49, 4, 2, 4, 'Beautiful, and I didn''t fully follow it. It kept working on me afterwards.', '很美但看不太懂后劲挺大', 'zh'),
  (37, 4, 4, 5, 'The chestburster. Permanently lodged in there.', '破胸而出那段永远的经典阴影', 'zh'),
  (16, 5, 2, 4, 'Best of the doll films. I threw the remote.', '娃娃类天花板吓到把遥控器扔了', 'zh'),
  (5, 3, 4, 4, 'That bear''s voice. Do not think about it at 3am.', '那只熊的叫声半夜不敢想', 'zh'),
  (12, 3, 5, 4, 'Cult horror that turns genuinely brutal in the back half.', '邪教题材后半段太狠', 'zh'),
  (58, 3, 5, 4, 'The second half made me physically uncomfortable. Curled my toes.', '后半段生理不适脚趾抠地', 'zh'),
  (34, 5, 4, 4, 'DO NOT go in the basement. Please.', '地下室千万别下去啊啊啊', 'zh'),
  (68, 2, 5, 4, 'The revenge is so grim it just sits on your chest.', '复仇太惨看得很压抑', 'zh'),
  (27, 2, 5, 4, 'That one scene will give you nightmares. Consider yourself warned.', '那一幕真的会做噩梦慎点', 'zh'),
  (88, 3, 3, 3, 'Gorgeous. All that red really works.', '画面美红红的很带感', 'zh'),
  (115, 4, 4, 4, 'You could not pay me to say it in front of a mirror.', '镜子前打死不敢念名字', 'zh'),
  (107, 4, 3, 3, 'The prom bucket. Untouchable.', '毕业舞会那一桶血封神', 'zh'),
  (19, 3, 4, 4, 'Cage goes fully unhinged and the colour is deeply wrong.', '凯奇疯了颜色好诡异', 'zh'),
  (128, 3, 1, 5, 'His smile is creepier than any ghost.', '男主的笑比鬼还渗人', 'zh'),
  (71, 1, 2, 3, 'Slow, and I didn''t get all of it, but it lingers.', '太闷了看不太懂但有点后劲', 'zh'),
  (60, 3, 1, 4, 'Scared me and made me want to cry. That mother goes through it.', '又吓又想哭妈妈太不容易', 'zh'),
  (15, 5, 2, 4, 'Puppets plus that score. I''m out.', '娃娃加这配乐我直接告辞', 'zh'),
  (101, 3, 4, 3, 'Old, and the kills still land hard.', '老片了但杀人场面还是狠', 'zh'),
  (83, 3, 2, 3, 'More sad than scary.', '更多是难过不是吓', 'zh'),
  (96, 2, 3, 3, 'Slow, slow, slow — then the ending jumps you.', '节奏好慢结尾突然吓一跳', 'zh'),
  (80, 3, 4, 3, 'Taiwanese, oppressive, and heavier than I expected.', '台湾片氛围压抑有点重口', 'zh'),
  (82, 1, 4, 4, 'Once you know what''s in them you don''t eat for days.', '知道内容后好几天吃不下饭', 'zh'),
  (114, 3, 5, 2, 'So much blood it becomes funny. Not actually frightening.', '血浆多到搞笑其实没那么怕', 'zh'),
  (63, 4, 2, 4, 'The exhumation scene put every hair on end.', '最近超火挖坟那段汗毛立起来', 'zh'),
  (97, 2, 4, 4, 'The face scene. A film this old should not still work.', '换脸那段老片也能吓到', 'zh'),
  (35, 3, 3, 4, 'The more you think the worse it gets. Less fear than suffocation.', '细思极恐比起吓更多是憋屈', 'zh'),
  (64, 5, 2, 5, 'Best of the livestream-dare films. Watched most of it through my fingers.', '直播探险类顶级全程捂眼', 'zh'),
  (105, 3, 4, 4, 'The twist, and then that scene. Rough.', '反转加上那段太难受了', 'zh'),
  (41, 4, 3, 4, 'The masked man just standing there is the scariest part.', '面具男站那不动最吓', 'zh'),
  (131, 5, 1, 5, 'The clown that doesn''t move is the worst thing in it.', '那个小丑站着不动才最恐怖', 'zh'),
  (111, 2, 5, 4, 'Pinhead and the hooks. Too much flesh for me.', '针头人加钩子肉太重口', 'zh'),
  (0, 4, 4, 5, 'Left me low all day. The car scene broke me.', '看完emo一整天那段车祸我裂开', 'zh'),
  (132, 5, 2, 4, 'The thing in the walls made me jump out of my seat.', '墙里的东西吓到跳起来', 'zh'),
  (74, 2, 2, 1, 'Psychedelic and silly. Not scary at all, genuinely funny.', '迷幻搞怪一点都不吓超好笑', 'zh'),
  (127, 4, 3, 4, 'A deaf woman against an intruder. Unbearably tense.', '聋哑女主对抗入室太紧张了', 'zh'),
  (28, 3, 5, 4, 'So violent it just knots you up.', '太暴力了看得心里发堵', 'zh'),
  (87, 4, 4, 4, 'Indonesian folk horror. Wrong and bloody in equal measure.', '印尼民俗恐怖又邪又血', 'zh'),
  (62, 5, 3, 5, 'It makes you chant to undo the curse. That stayed with me.', '看完还要念咒解咒心理阴影', 'zh'),
  (100, 4, 5, 4, 'The pregnancy angle is merciless. Genuinely think twice.', '孕妇题材太狠了真的慎入', 'zh'),
  (121, 5, 1, 4, 'The red-faced thing plus that score. Terrifying.', '红脸鬼加配乐吓破胆', 'zh'),
  (129, 5, 3, 3, 'If clowns are your thing, walk away now.', '小丑恐惧症请务必绕道', 'zh'),
  (21, 3, 2, 5, 'Something walking toward you, always. Deeply unnerving.', '走着过来的那个东西太瘆人', 'zh'),
  (57, 4, 2, 5, 'That throat sound. I will never forget it.', '那个咕噜声一辈子忘不掉', 'zh'),
  (103, 3, 4, 5, 'The ending left me stunned, and worse the longer I thought.', '结局给我看懵了细思极恐', 'zh'),
  (72, 1, 1, 3, 'Like watching paintings. Beautiful, not frightening.', '像在看画很美但不吓', 'zh'),
  (123, 2, 1, 4, 'When they zoom in on that photo, cold down the spine.', '那张照片放大后后背发凉', 'zh'),
  (13, 2, 2, 3, 'More uncanny than scary.', '更多是诡异不是吓人', 'zh'),
  (52, 4, 3, 4, 'The retro live-broadcast setup. Could not stop watching.', '复古直播设定看得停不下来', 'zh'),
  (98, 3, 3, 3, 'A vampire film that is tender and cruel at once.', '又温柔又残忍的吸血鬼片', 'zh'),
  (51, 4, 3, 5, 'The atmosphere is smothering and Cage is deeply strange.', '氛围压得慌凯奇太诡异了', 'zh'),
  (135, 4, 2, 2, 'Less frightening than funny and very watchable.', '与其说怕不如说好笑又好看', 'zh'),
  (18, 2, 4, 3, 'So hallucinatory it plays like an actual nightmare.', '太迷幻了像在做噩梦', 'zh'),
  (99, 4, 5, 5, 'Don''t. Seriously, don''t. It sits on you for days.', '别看真的别看会难受好几天', 'zh'),
  (1, 3, 5, 4, 'Broad daylight makes it worse. No company retreats for me.', '大白天更瘆人看完不敢去团建', 'zh'),
  (78, 2, 1, 1, 'Childhood memory. Far more funny than frightening.', '童年回忆搞笑多过吓人', 'zh'),
  (46, 3, 3, 4, 'The thing in the sky gets worse the more you think about it.', '天上那个东西越想越怕', 'zh'),
  (59, 3, 2, 4, 'Mockumentary that creeps up on you. A little long.', '伪纪录片细思极恐但有点长', 'zh'),
  (54, 1, 1, 3, 'So old it plays more as history than horror now.', '太老了现在看更多是历史感', 'zh'),
  (53, 5, 3, 4, 'That wooden figure, just sitting there. Awful.', '那个人偶坐在那儿太吓了', 'zh'),
  (75, 2, 2, 1, 'It''s actually a warm comedy. Go in without fear.', '其实是部温暖喜剧放心大胆看', 'zh'),
  (73, 3, 2, 4, 'The mask that won''t come off. Horrible.', '那张鬼面具摘不下来太吓', 'zh'),
  (79, 3, 2, 2, 'Hong Kong horror-comedy. Laughing with a jolt underneath.', '港式恐怖喜剧笑中带吓', 'zh'),
  (124, 5, 1, 5, 'After the dragging scene I slept with the light on.', '半夜被拖走那段之后不敢关灯睡', 'zh'),
  (24, 2, 3, 3, 'Lovely colours, and her smile is not right.', '色彩好看女主笑起来毛毛的', 'zh'),
  (109, 4, 3, 3, 'Static on a TV screen has never been the same.', '电视雪花屏从此有阴影', 'zh'),
  (95, 3, 4, 5, 'Her performance is frightening. I didn''t follow it and it still hurt.', '女主演技吓人看不懂但很难受', 'zh'),
  (7, 3, 5, 4, 'Body-swapping plus the gore. Ferocious.', '换脑设定加血腥场面很生猛', 'zh'),
  (14, 2, 1, 5, 'That spider puppet is raw nightmare material.', '那个蜘蛛人偶噩梦素材', 'zh'),
  (38, 4, 2, 4, 'I hear those strings every time I shower.', '洗澡都会想起那段配乐', 'zh'),
  (10, 3, 1, 4, 'The shape that slowly walks toward you. Deathly.', '那个慢慢走过来的黑影阴间', 'zh'),
  (55, 2, 5, 3, 'The raw meat scene made me physically ill.', '吃生肉那段生理性不适', 'zh'),
  (113, 3, 5, 2, 'A gore machine, but mostly gleeful rather than scary.', '血浆狂魔但更多是猎奇好笑', 'zh'),
  (77, 4, 3, 3, 'Full of Hong Kong nostalgia and the mood is immaculate.', '港片情怀氛围做得很足', 'zh'),
  (9, 4, 1, 5, 'Sadako coming out of the TV. Childhood, ruined.', '贞子爬出电视那幕童年阴影', 'zh'),
  (39, 2, 1, 4, 'Slow, but being conspired against like that is suffocating.', '节奏慢但那种被算计的感觉窒息', 'zh'),
  (3, 3, 2, 4, 'Faith curdling into something else. It made me anxious.', '宗教走火入魔看得心里发慌', 'zh'),
  (86, 5, 2, 4, 'That bell rings and I flinch. Indonesia can really do this.', '铃铛一响我就抖印尼真的会吓人', 'zh'),
  (116, 4, 3, 3, 'Mask, phone, killer. Thrilling and genuinely fun.', '面具电话杀手又刺激又好玩', 'zh'),
  (119, 3, 2, 4, 'An abandoned asylum that gets under you slowly.', '废弃精神病院越看越渗人', 'zh'),
  (61, 5, 2, 5, 'That final photo, and the shoulders. Untouchable.', '结局那张照片加肩膀直接封神', 'zh'),
  (120, 5, 3, 5, 'Those home movies. And the lawnmower.', '那些家庭录像加割草机太吓了', 'zh'),
  (67, 4, 2, 4, 'Sleepwalking as a premise. It tightens as it goes.', '梦游设定新颖越看越慌', 'zh'),
  (134, 5, 3, 4, 'That smile, appearing without warning. My heart couldn''t take it.', '那个笑容加突然出现心脏受不了', 'zh'),
  (106, 2, 3, 5, 'Squirming the whole time, then furious.', '全程如坐针毡气到想骂人', 'zh'),
  (89, 3, 1, 2, 'Indian horror with songs. More laughs than scares.', '印度恐怖歌舞笑点比吓点多', 'zh'),
  (8, 4, 4, 4, 'Colours to die for, and the killing is its own art.', '色彩美到窒息杀人也很艺术', 'zh'),
  (25, 5, 4, 4, 'The handshake possession is addictive and terrifying.', '握手降灵那个设定太上头也太吓', 'zh'),
  (92, 5, 3, 5, 'The thing crawling out from under the bed. I lost it.', '床底下爬出来那段我当场裂开', 'zh'),
  (30, 3, 5, 3, 'Bloody enough that I quit. One more reason to fear clowns.', '血腥到弃剧小丑恐惧再加一', 'zh'),
  (76, 2, 4, 3, 'Loud, strange, and I couldn''t sit through it.', '又吵又怪实在看不下去', 'zh'),
  (126, 5, 4, 5, 'A morgue, and then the body opens its eyes.', '验尸房加尸体睁眼太吓人了', 'zh'),
  (43, 4, 1, 4, 'That pop-up book, and the shadow. Horrible.', '那本弹出书加影子好瘆人', 'zh'),
  (102, 2, 5, 3, 'Vintage Italian gore. Strong stuff.', '意式血浆老片重口向', 'zh'),
  (44, 3, 1, 4, null, null, null)
) as v(movie_idx, jumps, gore, dread, note, note_original, note_lang);

-- check
select count(*) as rows_total, count(note) as with_notes from public.user_ratings where source = 'offline';
select movie_idx, left(note, 46) from public.movie_notes limit 5;
