// Regenerates api/_catalog.mjs from the M array in index.html.
// Run after editing the movie list: node scripts/build-catalog.mjs
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
// M array lives in movies.js (falls back to inline index.html for older layouts)
let source;
try { source = readFileSync(join(root, 'movies.js'), 'utf8'); }
catch { source = readFileSync(join(root, 'index.html'), 'utf8'); }

const match = source.match(/const M = \[([\s\S]*?)\n\];/);
if (!match) throw new Error('Could not find `const M = [...]` in movies.js or index.html');

const movies = new Function(`return [${match[1]}]`)();

const catalog = movies.map((m, id) => ({
  id,
  title: m.t,
  year: m.y,
  director: m.d,
  tags: m.tags,
  scare: m.scare,
  gore: m.gore,
  dread: m.dread,
  gem: !!m.obscure,
  streaming: m.str || [],
  imdb: m.imdb ?? null,
  douban: m.db ?? null,
}));

const out = `// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit by hand.
// ids match the index of the M array in index.html.
export const CATALOG = ${JSON.stringify(catalog, null, 2)};
`;

writeFileSync(join(root, 'api', '_catalog.mjs'), out);
console.log(`Wrote api/_catalog.mjs with ${catalog.length} films`);
