// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit by hand.
// ids match the index of the M array in index.html.
export const CATALOG = [
  {
    "id": 0,
    "title": "Hereditary",
    "year": 2018,
    "director": "Ari Aster",
    "tags": [
      "a24",
      "occult",
      "grief",
      "slow-burn",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Apple TV+",
      "Paramount+"
    ]
  },
  {
    "id": 1,
    "title": "Midsommar",
    "year": 2019,
    "director": "Ari Aster",
    "tags": [
      "a24",
      "folk",
      "cult",
      "grief",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Apple TV+"
    ]
  },
  {
    "id": 2,
    "title": "The Witch",
    "year": 2015,
    "director": "Robert Eggers",
    "tags": [
      "folk",
      "religious",
      "slow-burn",
      "witch",
      "isolation",
      "a24"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+",
      "Shudder"
    ]
  },
  {
    "id": 3,
    "title": "Saint Maud",
    "year": 2019,
    "director": "Rose Glass",
    "tags": [
      "religious",
      "psychological",
      "slow-burn",
      "isolation",
      "a24"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Hulu",
      "Paramount+"
    ]
  },
  {
    "id": 4,
    "title": "The Exorcist",
    "year": 1973,
    "director": "William Friedkin",
    "tags": [
      "religious",
      "possession",
      "supernatural"
    ],
    "scare": 5,
    "gore": 3,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Max",
      "Peacock"
    ]
  },
  {
    "id": 5,
    "title": "Annihilation",
    "year": 2018,
    "director": "Alex Garland",
    "tags": [
      "cosmic",
      "body-horror",
      "atmospheric",
      "psychological"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+",
      "Hulu"
    ]
  },
  {
    "id": 6,
    "title": "The Thing",
    "year": 1982,
    "director": "John Carpenter",
    "tags": [
      "body-horror",
      "creature",
      "isolation",
      "paranoia"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Peacock"
    ]
  },
  {
    "id": 7,
    "title": "Possessor",
    "year": 2020,
    "director": "Brandon Cronenberg",
    "tags": [
      "body-horror",
      "psychological",
      "gore",
      "cosmic"
    ],
    "scare": 3,
    "gore": 5,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Hulu"
    ]
  },
  {
    "id": 8,
    "title": "Suspiria",
    "year": 1977,
    "director": "Dario Argento",
    "tags": [
      "giallo",
      "witch",
      "supernatural",
      "atmospheric",
      "gore"
    ],
    "scare": 4,
    "gore": 4,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Tubi",
      "Shudder"
    ]
  },
  {
    "id": 9,
    "title": "Ringu",
    "year": 1998,
    "director": "Hideo Nakata",
    "tags": [
      "j-horror",
      "supernatural",
      "psychological",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 10,
    "title": "Pulse",
    "year": 2001,
    "director": "Kiyoshi Kurosawa",
    "tags": [
      "j-horror",
      "supernatural",
      "isolation",
      "cosmic",
      "atmospheric"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 11,
    "title": "The Wicker Man",
    "year": 1973,
    "director": "Robin Hardy",
    "tags": [
      "folk",
      "cult",
      "religious",
      "isolation"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Tubi"
    ]
  },
  {
    "id": 12,
    "title": "Apostle",
    "year": 2018,
    "director": "Gareth Evans",
    "tags": [
      "folk",
      "cult",
      "religious",
      "gore"
    ],
    "scare": 3,
    "gore": 5,
    "dread": 3,
    "gem": true,
    "streaming": [
      "Netflix"
    ]
  },
  {
    "id": 13,
    "title": "Lamb",
    "year": 2021,
    "director": "V. Jóhannsson",
    "tags": [
      "folk",
      "atmospheric",
      "slow-burn",
      "isolation",
      "a24"
    ],
    "scare": 1,
    "gore": 1,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Prime Video"
    ]
  },
  {
    "id": 14,
    "title": "Possum",
    "year": 2018,
    "director": "Matthew Holness",
    "tags": [
      "dolls",
      "psychological",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 15,
    "title": "Dead Silence",
    "year": 2007,
    "director": "James Wan",
    "tags": [
      "dolls",
      "supernatural",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Peacock"
    ]
  },
  {
    "id": 16,
    "title": "Annabelle: Creation",
    "year": 2017,
    "director": "David Sandberg",
    "tags": [
      "dolls",
      "supernatural",
      "possession",
      "religious"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Max",
      "Netflix"
    ]
  },
  {
    "id": 17,
    "title": "The Boy",
    "year": 2016,
    "director": "W.B. Bell",
    "tags": [
      "dolls",
      "isolation",
      "psychological",
      "supernatural"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Netflix"
    ]
  },
  {
    "id": 18,
    "title": "Mandy",
    "year": 2018,
    "director": "Panos Cosmatos",
    "tags": [
      "cult",
      "revenge",
      "atmospheric",
      "cosmic",
      "gore"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Shudder",
      "Tubi"
    ]
  },
  {
    "id": 19,
    "title": "Color Out of Space",
    "year": 2019,
    "director": "Richard Stanley",
    "tags": [
      "cosmic",
      "body-horror",
      "isolation",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 20,
    "title": "The Lighthouse",
    "year": 2019,
    "director": "Robert Eggers",
    "tags": [
      "cosmic",
      "isolation",
      "psychological",
      "atmospheric",
      "a24"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Prime Video"
    ]
  },
  {
    "id": 21,
    "title": "It Follows",
    "year": 2014,
    "director": "D.R. Mitchell",
    "tags": [
      "supernatural",
      "slow-burn",
      "atmospheric",
      "psychological"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+",
      "Tubi"
    ]
  },
  {
    "id": 22,
    "title": "The Ritual",
    "year": 2017,
    "director": "David Bruckner",
    "tags": [
      "folk",
      "creature",
      "isolation",
      "grief"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Netflix"
    ]
  },
  {
    "id": 23,
    "title": "X",
    "year": 2022,
    "director": "Ti West",
    "tags": [
      "slasher",
      "a24",
      "gore",
      "isolation"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Paramount+",
      "Showtime"
    ]
  },
  {
    "id": 24,
    "title": "Pearl",
    "year": 2022,
    "director": "Ti West",
    "tags": [
      "slasher",
      "psychological",
      "a24",
      "isolation"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Paramount+",
      "Showtime"
    ]
  },
  {
    "id": 25,
    "title": "Talk to Me",
    "year": 2022,
    "director": "Philippou Bros.",
    "tags": [
      "possession",
      "supernatural",
      "a24",
      "grief"
    ],
    "scare": 5,
    "gore": 3,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Prime Video",
      "Paramount+"
    ]
  },
  {
    "id": 26,
    "title": "The Conjuring",
    "year": 2013,
    "director": "James Wan",
    "tags": [
      "supernatural",
      "possession",
      "religious"
    ],
    "scare": 5,
    "gore": 2,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Max",
      "Netflix"
    ]
  },
  {
    "id": 27,
    "title": "Bone Tomahawk",
    "year": 2015,
    "director": "S.C. Zahler",
    "tags": [
      "gore",
      "isolation",
      "slow-burn",
      "creature"
    ],
    "scare": 3,
    "gore": 5,
    "dread": 3,
    "gem": true,
    "streaming": [
      "Tubi",
      "Pluto TV"
    ]
  },
  {
    "id": 28,
    "title": "I Saw the Devil",
    "year": 2010,
    "director": "Kim Jee-woon",
    "tags": [
      "revenge",
      "psychological",
      "gore",
      "slasher"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 3,
    "gem": true,
    "streaming": [
      "Tubi",
      "Shudder"
    ]
  },
  {
    "id": 29,
    "title": "Under the Skin",
    "year": 2013,
    "director": "Jonathan Glazer",
    "tags": [
      "cosmic",
      "atmospheric",
      "slow-burn",
      "a24",
      "body-horror"
    ],
    "scare": 2,
    "gore": 2,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Max"
    ]
  },
  {
    "id": 30,
    "title": "Terrifier 2",
    "year": 2022,
    "director": "Damien Leone",
    "tags": [
      "slasher",
      "gore",
      "dolls"
    ],
    "scare": 5,
    "gore": 5,
    "dread": 1,
    "gem": false,
    "streaming": [
      "Screambox",
      "Tubi"
    ]
  },
  {
    "id": 31,
    "title": "The Void",
    "year": 2016,
    "director": "Gillespie & Kostanski",
    "tags": [
      "cosmic",
      "body-horror",
      "cult",
      "creature"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Tubi",
      "Shudder"
    ]
  },
  {
    "id": 32,
    "title": "Tumbbad",
    "year": 2018,
    "director": "Rahi Anil Barve",
    "tags": [
      "folk",
      "atmospheric",
      "creature",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Prime Video"
    ]
  },
  {
    "id": 33,
    "title": "The Orphanage",
    "year": 2007,
    "director": "J.A. Bayona",
    "tags": [
      "supernatural",
      "grief",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Max",
      "Tubi"
    ]
  },
  {
    "id": 34,
    "title": "Barbarian",
    "year": 2022,
    "director": "Zach Cregger",
    "tags": [
      "isolation",
      "psychological",
      "creature",
      "gore"
    ],
    "scare": 5,
    "gore": 4,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Max",
      "Hulu"
    ]
  },
  {
    "id": 35,
    "title": "Get Out",
    "year": 2017,
    "director": "Jordan Peele",
    "tags": [
      "psychological",
      "slow-burn",
      "supernatural"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Peacock"
    ]
  },
  {
    "id": 36,
    "title": "The Shining",
    "year": 1980,
    "director": "Stanley Kubrick",
    "tags": [
      "psychological",
      "isolation",
      "atmospheric",
      "supernatural"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Max"
    ]
  },
  {
    "id": 37,
    "title": "Alien",
    "year": 1979,
    "director": "Ridley Scott",
    "tags": [
      "creature",
      "isolation",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 5,
    "gore": 3,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Hulu"
    ]
  },
  {
    "id": 38,
    "title": "Psycho",
    "year": 1960,
    "director": "Alfred Hitchcock",
    "tags": [
      "psychological",
      "slasher"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Peacock"
    ]
  },
  {
    "id": 39,
    "title": "Rosemary's Baby",
    "year": 1968,
    "director": "Roman Polanski",
    "tags": [
      "occult",
      "psychological",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+"
    ]
  },
  {
    "id": 40,
    "title": "The Texas Chain Saw Massacre",
    "year": 1974,
    "director": "Tobe Hooper",
    "tags": [
      "slasher",
      "isolation",
      "gore"
    ],
    "scare": 5,
    "gore": 5,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Tubi",
      "Shudder"
    ]
  },
  {
    "id": 41,
    "title": "Halloween",
    "year": 1978,
    "director": "John Carpenter",
    "tags": [
      "slasher",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Shudder",
      "Peacock"
    ]
  },
  {
    "id": 42,
    "title": "A Quiet Place",
    "year": 2018,
    "director": "John Krasinski",
    "tags": [
      "creature",
      "atmospheric",
      "isolation"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+"
    ]
  },
  {
    "id": 43,
    "title": "The Babadook",
    "year": 2014,
    "director": "Jennifer Kent",
    "tags": [
      "psychological",
      "grief",
      "supernatural"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Tubi",
      "Shudder"
    ]
  },
  {
    "id": 44,
    "title": "The Blair Witch Project",
    "year": 1999,
    "director": "Myrick & Sánchez",
    "tags": [
      "found-footage",
      "folk",
      "isolation",
      "atmospheric"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+"
    ]
  },
  {
    "id": 45,
    "title": "The Descent",
    "year": 2005,
    "director": "Neil Marshall",
    "tags": [
      "creature",
      "isolation",
      "gore",
      "atmospheric"
    ],
    "scare": 5,
    "gore": 4,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Tubi",
      "Pluto TV"
    ]
  },
  {
    "id": 46,
    "title": "Nope",
    "year": 2022,
    "director": "Jordan Peele",
    "tags": [
      "cosmic",
      "creature",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Peacock"
    ]
  },
  {
    "id": 47,
    "title": "Train to Busan",
    "year": 2016,
    "director": "Sang-ho Yeon",
    "tags": [
      "zombie",
      "grief",
      "isolation"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Shudder",
      "Tubi"
    ]
  },
  {
    "id": 48,
    "title": "The Wailing",
    "year": 2016,
    "director": "Na Hong-jin",
    "tags": [
      "folk",
      "supernatural",
      "religious",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Prime Video",
      "Shudder"
    ]
  },
  {
    "id": 49,
    "title": "A Tale of Two Sisters",
    "year": 2003,
    "director": "Kim Jee-woon",
    "tags": [
      "psychological",
      "supernatural",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 50,
    "title": "The Substance",
    "year": 2024,
    "director": "Coralie Fargeat",
    "tags": [
      "body-horror",
      "psychological",
      "gore"
    ],
    "scare": 3,
    "gore": 5,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Mubi"
    ]
  },
  {
    "id": 51,
    "title": "Longlegs",
    "year": 2024,
    "director": "Osgood Perkins",
    "tags": [
      "psychological",
      "occult",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Hulu"
    ]
  },
  {
    "id": 52,
    "title": "Late Night with the Devil",
    "year": 2023,
    "director": "Cameron Cairnes",
    "tags": [
      "supernatural",
      "possession",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 53,
    "title": "Oddity",
    "year": 2024,
    "director": "Damian McCarthy",
    "tags": [
      "supernatural",
      "psychological",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 54,
    "title": "Nosferatu",
    "year": 2024,
    "director": "Robert Eggers",
    "tags": [
      "supernatural",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Peacock"
    ]
  },
  {
    "id": 55,
    "title": "Raw",
    "year": 2016,
    "director": "Julia Ducournau",
    "tags": [
      "body-horror",
      "psychological",
      "gore"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 56,
    "title": "[REC]",
    "year": 2007,
    "director": "Jaume Balagueró",
    "tags": [
      "found-footage",
      "zombie",
      "isolation"
    ],
    "scare": 5,
    "gore": 4,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Tubi"
    ]
  },
  {
    "id": 57,
    "title": "Ju-On: The Grudge",
    "year": 2002,
    "director": "Takashi Shimizu",
    "tags": [
      "j-horror",
      "supernatural",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 1,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 58,
    "title": "Audition",
    "year": 1999,
    "director": "Takashi Miike",
    "tags": [
      "j-horror",
      "psychological",
      "gore",
      "slow-burn"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 59,
    "title": "Noroi: The Curse",
    "year": 2005,
    "director": "Kōji Shiraishi",
    "tags": [
      "j-horror",
      "found-footage",
      "supernatural",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 60,
    "title": "Dark Water",
    "year": 2002,
    "director": "Hideo Nakata",
    "tags": [
      "j-horror",
      "supernatural",
      "grief",
      "atmospheric"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 61,
    "title": "Shutter",
    "year": 2004,
    "director": "B. Pisanthanakun",
    "tags": [
      "supernatural",
      "psychological",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 1,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Shudder"
    ]
  },
  {
    "id": 62,
    "title": "Incantation",
    "year": 2022,
    "director": "Kevin Ko",
    "tags": [
      "found-footage",
      "folk",
      "supernatural",
      "religious"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Netflix"
    ]
  }
];
