// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit by hand.
// ids match the index of the M array in index.html.
export const CATALOG = [
  {
    "id": 0,
    "title": "Hereditary",
    "year": 2018,
    "director": "Ari Aster",
    "tags": [
      "a24",
      "occult",
      "grief",
      "slow-burn",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Apple TV+",
      "Paramount+"
    ],
    "imdb": 7.3,
    "douban": 7.4
  },
  {
    "id": 1,
    "title": "Midsommar",
    "year": 2019,
    "director": "Ari Aster",
    "tags": [
      "a24",
      "folk",
      "cult",
      "grief",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Apple TV+"
    ],
    "imdb": 7.1,
    "douban": 7
  },
  {
    "id": 2,
    "title": "The Witch",
    "year": 2015,
    "director": "Robert Eggers",
    "tags": [
      "folk",
      "religious",
      "slow-burn",
      "witch",
      "isolation",
      "a24"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+",
      "Shudder"
    ],
    "imdb": 7,
    "douban": 7.1
  },
  {
    "id": 3,
    "title": "Saint Maud",
    "year": 2019,
    "director": "Rose Glass",
    "tags": [
      "religious",
      "psychological",
      "slow-burn",
      "isolation",
      "a24"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Hulu",
      "Paramount+"
    ],
    "imdb": 6.6,
    "douban": null
  },
  {
    "id": 4,
    "title": "The Exorcist",
    "year": 1973,
    "director": "William Friedkin",
    "tags": [
      "religious",
      "possession",
      "supernatural"
    ],
    "scare": 5,
    "gore": 3,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Max",
      "Peacock"
    ],
    "imdb": 8.1,
    "douban": 7.7
  },
  {
    "id": 5,
    "title": "Annihilation",
    "year": 2018,
    "director": "Alex Garland",
    "tags": [
      "cosmic",
      "body-horror",
      "atmospheric",
      "psychological"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+",
      "Hulu"
    ],
    "imdb": 6.8,
    "douban": 7.2
  },
  {
    "id": 6,
    "title": "The Thing",
    "year": 1982,
    "director": "John Carpenter",
    "tags": [
      "body-horror",
      "creature",
      "isolation",
      "paranoia"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Peacock"
    ],
    "imdb": 8.2,
    "douban": 8.2
  },
  {
    "id": 7,
    "title": "Possessor",
    "year": 2020,
    "director": "Brandon Cronenberg",
    "tags": [
      "body-horror",
      "psychological",
      "gore",
      "cosmic"
    ],
    "scare": 3,
    "gore": 5,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Hulu"
    ],
    "imdb": 6.5,
    "douban": 6
  },
  {
    "id": 8,
    "title": "Suspiria",
    "year": 1977,
    "director": "Dario Argento",
    "tags": [
      "giallo",
      "witch",
      "supernatural",
      "atmospheric",
      "gore"
    ],
    "scare": 4,
    "gore": 4,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Tubi",
      "Shudder"
    ],
    "imdb": 7.3,
    "douban": 7.6
  },
  {
    "id": 9,
    "title": "Ringu",
    "year": 1998,
    "director": "Hideo Nakata",
    "tags": [
      "j-horror",
      "supernatural",
      "psychological",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Shudder"
    ],
    "imdb": 7.2,
    "douban": 7.6
  },
  {
    "id": 10,
    "title": "Pulse",
    "year": 2001,
    "director": "Kiyoshi Kurosawa",
    "tags": [
      "j-horror",
      "supernatural",
      "isolation",
      "cosmic",
      "atmospheric"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.6,
    "douban": 7.3
  },
  {
    "id": 11,
    "title": "The Wicker Man",
    "year": 1973,
    "director": "Robin Hardy",
    "tags": [
      "folk",
      "cult",
      "religious",
      "isolation"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Tubi"
    ],
    "imdb": 7.5,
    "douban": 8
  },
  {
    "id": 12,
    "title": "Apostle",
    "year": 2018,
    "director": "Gareth Evans",
    "tags": [
      "folk",
      "cult",
      "religious",
      "gore"
    ],
    "scare": 3,
    "gore": 5,
    "dread": 3,
    "gem": true,
    "streaming": [
      "Netflix"
    ],
    "imdb": 6.3,
    "douban": 6.3
  },
  {
    "id": 13,
    "title": "Lamb",
    "year": 2021,
    "director": "V. Jóhannsson",
    "tags": [
      "folk",
      "atmospheric",
      "slow-burn",
      "isolation",
      "a24"
    ],
    "scare": 1,
    "gore": 1,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Prime Video"
    ],
    "imdb": 6.3,
    "douban": 5.9
  },
  {
    "id": 14,
    "title": "Possum",
    "year": 2018,
    "director": "Matthew Holness",
    "tags": [
      "dolls",
      "psychological",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 5.8,
    "douban": 5.1
  },
  {
    "id": 15,
    "title": "Dead Silence",
    "year": 2007,
    "director": "James Wan",
    "tags": [
      "dolls",
      "supernatural",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Peacock"
    ],
    "imdb": 6.2,
    "douban": 7.9
  },
  {
    "id": 16,
    "title": "Annabelle: Creation",
    "year": 2017,
    "director": "David Sandberg",
    "tags": [
      "dolls",
      "supernatural",
      "possession",
      "religious"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Max",
      "Netflix"
    ],
    "imdb": 6.5,
    "douban": 6.9
  },
  {
    "id": 17,
    "title": "The Boy",
    "year": 2016,
    "director": "W.B. Bell",
    "tags": [
      "dolls",
      "isolation",
      "psychological",
      "supernatural"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Netflix"
    ],
    "imdb": 6,
    "douban": 6.2
  },
  {
    "id": 18,
    "title": "Mandy",
    "year": 2018,
    "director": "Panos Cosmatos",
    "tags": [
      "cult",
      "revenge",
      "atmospheric",
      "cosmic",
      "gore"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Shudder",
      "Tubi"
    ],
    "imdb": 6.5,
    "douban": 5.4
  },
  {
    "id": 19,
    "title": "Color Out of Space",
    "year": 2019,
    "director": "Richard Stanley",
    "tags": [
      "cosmic",
      "body-horror",
      "isolation",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.1,
    "douban": 6.5
  },
  {
    "id": 20,
    "title": "The Lighthouse",
    "year": 2019,
    "director": "Robert Eggers",
    "tags": [
      "cosmic",
      "isolation",
      "psychological",
      "atmospheric",
      "a24"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Prime Video"
    ],
    "imdb": 7.4,
    "douban": 7.3
  },
  {
    "id": 21,
    "title": "It Follows",
    "year": 2014,
    "director": "D.R. Mitchell",
    "tags": [
      "supernatural",
      "slow-burn",
      "atmospheric",
      "psychological"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+",
      "Tubi"
    ],
    "imdb": 6.8,
    "douban": 6.4
  },
  {
    "id": 22,
    "title": "The Ritual",
    "year": 2017,
    "director": "David Bruckner",
    "tags": [
      "folk",
      "creature",
      "isolation",
      "grief"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Netflix"
    ],
    "imdb": 6.4,
    "douban": 6.3
  },
  {
    "id": 23,
    "title": "X",
    "year": 2022,
    "director": "Ti West",
    "tags": [
      "slasher",
      "a24",
      "gore",
      "isolation"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Paramount+",
      "Showtime"
    ],
    "imdb": 6.5,
    "douban": 6.4
  },
  {
    "id": 24,
    "title": "Pearl",
    "year": 2022,
    "director": "Ti West",
    "tags": [
      "slasher",
      "psychological",
      "a24",
      "isolation"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Paramount+",
      "Showtime"
    ],
    "imdb": 7,
    "douban": 7.6
  },
  {
    "id": 25,
    "title": "Talk to Me",
    "year": 2022,
    "director": "Philippou Bros.",
    "tags": [
      "possession",
      "supernatural",
      "a24",
      "grief"
    ],
    "scare": 5,
    "gore": 3,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Prime Video",
      "Paramount+"
    ],
    "imdb": 7.1,
    "douban": 6.3
  },
  {
    "id": 26,
    "title": "The Conjuring",
    "year": 2013,
    "director": "James Wan",
    "tags": [
      "supernatural",
      "possession",
      "religious"
    ],
    "scare": 5,
    "gore": 2,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Max",
      "Netflix"
    ],
    "imdb": 7.5,
    "douban": 8.1
  },
  {
    "id": 27,
    "title": "Bone Tomahawk",
    "year": 2015,
    "director": "S.C. Zahler",
    "tags": [
      "gore",
      "isolation",
      "slow-burn",
      "creature"
    ],
    "scare": 3,
    "gore": 5,
    "dread": 3,
    "gem": true,
    "streaming": [
      "Tubi",
      "Pluto TV"
    ],
    "imdb": 7.1,
    "douban": 7
  },
  {
    "id": 28,
    "title": "I Saw the Devil",
    "year": 2010,
    "director": "Kim Jee-woon",
    "tags": [
      "k-horror",
      "revenge",
      "psychological",
      "gore",
      "slasher"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 3,
    "gem": true,
    "streaming": [
      "Tubi",
      "Shudder"
    ],
    "imdb": 7.8,
    "douban": 7.9
  },
  {
    "id": 29,
    "title": "Under the Skin",
    "year": 2013,
    "director": "Jonathan Glazer",
    "tags": [
      "cosmic",
      "atmospheric",
      "slow-burn",
      "a24",
      "body-horror"
    ],
    "scare": 2,
    "gore": 2,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Max"
    ],
    "imdb": 6.3,
    "douban": 6.3
  },
  {
    "id": 30,
    "title": "Terrifier 2",
    "year": 2022,
    "director": "Damien Leone",
    "tags": [
      "slasher",
      "gore",
      "dolls"
    ],
    "scare": 5,
    "gore": 5,
    "dread": 1,
    "gem": false,
    "streaming": [
      "Screambox",
      "Tubi"
    ],
    "imdb": 6,
    "douban": 5.9
  },
  {
    "id": 31,
    "title": "The Void",
    "year": 2016,
    "director": "Gillespie & Kostanski",
    "tags": [
      "cosmic",
      "body-horror",
      "cult",
      "creature"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Tubi",
      "Shudder"
    ],
    "imdb": 5.9,
    "douban": 6.2
  },
  {
    "id": 32,
    "title": "Tumbbad",
    "year": 2018,
    "director": "Rahi Anil Barve",
    "tags": [
      "folk",
      "atmospheric",
      "creature",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Prime Video"
    ],
    "imdb": 8.2,
    "douban": 7.5
  },
  {
    "id": 33,
    "title": "The Orphanage",
    "year": 2007,
    "director": "J.A. Bayona",
    "tags": [
      "supernatural",
      "grief",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Max",
      "Tubi"
    ],
    "imdb": 7.4,
    "douban": 7.4
  },
  {
    "id": 34,
    "title": "Barbarian",
    "year": 2022,
    "director": "Zach Cregger",
    "tags": [
      "isolation",
      "psychological",
      "creature",
      "gore"
    ],
    "scare": 5,
    "gore": 4,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Max",
      "Hulu"
    ],
    "imdb": 7,
    "douban": 6.8
  },
  {
    "id": 35,
    "title": "Get Out",
    "year": 2017,
    "director": "Jordan Peele",
    "tags": [
      "psychological",
      "slow-burn",
      "supernatural"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Peacock"
    ],
    "imdb": 7.8,
    "douban": 7.8
  },
  {
    "id": 36,
    "title": "The Shining",
    "year": 1980,
    "director": "Stanley Kubrick",
    "tags": [
      "psychological",
      "isolation",
      "atmospheric",
      "supernatural"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Max"
    ],
    "imdb": 8.4,
    "douban": 8.3
  },
  {
    "id": 37,
    "title": "Alien",
    "year": 1979,
    "director": "Ridley Scott",
    "tags": [
      "creature",
      "isolation",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 5,
    "gore": 3,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Hulu"
    ],
    "imdb": 8.4,
    "douban": 8.3
  },
  {
    "id": 38,
    "title": "Psycho",
    "year": 1960,
    "director": "Alfred Hitchcock",
    "tags": [
      "psychological",
      "slasher"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Peacock"
    ],
    "imdb": 8.5,
    "douban": 9
  },
  {
    "id": 39,
    "title": "Rosemary's Baby",
    "year": 1968,
    "director": "Roman Polanski",
    "tags": [
      "occult",
      "psychological",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+"
    ],
    "imdb": 8,
    "douban": 8.2
  },
  {
    "id": 40,
    "title": "The Texas Chain Saw Massacre",
    "year": 1974,
    "director": "Tobe Hooper",
    "tags": [
      "slasher",
      "isolation",
      "gore"
    ],
    "scare": 5,
    "gore": 5,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Tubi",
      "Shudder"
    ],
    "imdb": 7.4,
    "douban": 7.2
  },
  {
    "id": 41,
    "title": "Halloween",
    "year": 1978,
    "director": "John Carpenter",
    "tags": [
      "slasher",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Shudder",
      "Peacock"
    ],
    "imdb": 7.7,
    "douban": 6.8
  },
  {
    "id": 42,
    "title": "A Quiet Place",
    "year": 2018,
    "director": "John Krasinski",
    "tags": [
      "creature",
      "atmospheric",
      "isolation"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+"
    ],
    "imdb": 7.5,
    "douban": 6.3
  },
  {
    "id": 43,
    "title": "The Babadook",
    "year": 2014,
    "director": "Jennifer Kent",
    "tags": [
      "psychological",
      "grief",
      "supernatural"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Tubi",
      "Shudder"
    ],
    "imdb": 6.8,
    "douban": 6.6
  },
  {
    "id": 44,
    "title": "The Blair Witch Project",
    "year": 1999,
    "director": "Myrick & Sánchez",
    "tags": [
      "found-footage",
      "folk",
      "isolation",
      "atmospheric"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Paramount+"
    ],
    "imdb": 6.5,
    "douban": 6.4
  },
  {
    "id": 45,
    "title": "The Descent",
    "year": 2005,
    "director": "Neil Marshall",
    "tags": [
      "creature",
      "isolation",
      "gore",
      "atmospheric"
    ],
    "scare": 5,
    "gore": 4,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Tubi",
      "Pluto TV"
    ],
    "imdb": 7.2,
    "douban": null
  },
  {
    "id": 46,
    "title": "Nope",
    "year": 2022,
    "director": "Jordan Peele",
    "tags": [
      "cosmic",
      "creature",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Peacock"
    ],
    "imdb": 6.8,
    "douban": 6.9
  },
  {
    "id": 47,
    "title": "Train to Busan",
    "year": 2016,
    "director": "Sang-ho Yeon",
    "tags": [
      "k-horror",
      "zombie",
      "grief",
      "isolation"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Shudder",
      "Tubi"
    ],
    "imdb": 7.6,
    "douban": 8.6
  },
  {
    "id": 48,
    "title": "The Wailing",
    "year": 2016,
    "director": "Na Hong-jin",
    "tags": [
      "k-horror",
      "folk",
      "supernatural",
      "religious",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Prime Video",
      "Shudder"
    ],
    "imdb": 7.4,
    "douban": 7.3
  },
  {
    "id": 49,
    "title": "A Tale of Two Sisters",
    "year": 2003,
    "director": "Kim Jee-woon",
    "tags": [
      "k-horror",
      "psychological",
      "supernatural",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 7.1,
    "douban": 7.2
  },
  {
    "id": 50,
    "title": "The Substance",
    "year": 2024,
    "director": "Coralie Fargeat",
    "tags": [
      "body-horror",
      "psychological",
      "gore"
    ],
    "scare": 3,
    "gore": 5,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Mubi"
    ],
    "imdb": 7.2,
    "douban": 7.5
  },
  {
    "id": 51,
    "title": "Longlegs",
    "year": 2024,
    "director": "Osgood Perkins",
    "tags": [
      "psychological",
      "occult",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Hulu"
    ],
    "imdb": 6.5,
    "douban": null
  },
  {
    "id": 52,
    "title": "Late Night with the Devil",
    "year": 2023,
    "director": "Cameron Cairnes",
    "tags": [
      "supernatural",
      "possession",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Shudder"
    ],
    "imdb": 7,
    "douban": null
  },
  {
    "id": 53,
    "title": "Oddity",
    "year": 2024,
    "director": "Damian McCarthy",
    "tags": [
      "supernatural",
      "psychological",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.7,
    "douban": null
  },
  {
    "id": 54,
    "title": "Nosferatu",
    "year": 2024,
    "director": "Robert Eggers",
    "tags": [
      "supernatural",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Peacock"
    ],
    "imdb": 7.1,
    "douban": 5.9
  },
  {
    "id": 55,
    "title": "Raw",
    "year": 2016,
    "director": "Julia Ducournau",
    "tags": [
      "body-horror",
      "psychological",
      "gore"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.9,
    "douban": 7.1
  },
  {
    "id": 56,
    "title": "[REC]",
    "year": 2007,
    "director": "Jaume Balagueró",
    "tags": [
      "found-footage",
      "zombie",
      "isolation"
    ],
    "scare": 5,
    "gore": 4,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Tubi"
    ],
    "imdb": 7.4,
    "douban": 7.6
  },
  {
    "id": 57,
    "title": "Ju-On: The Grudge",
    "year": 2002,
    "director": "Takashi Shimizu",
    "tags": [
      "j-horror",
      "supernatural",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 1,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.7,
    "douban": 7.6
  },
  {
    "id": 58,
    "title": "Audition",
    "year": 1999,
    "director": "Takashi Miike",
    "tags": [
      "j-horror",
      "psychological",
      "gore",
      "slow-burn"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 7.1,
    "douban": null
  },
  {
    "id": 59,
    "title": "Noroi: The Curse",
    "year": 2005,
    "director": "Kōji Shiraishi",
    "tags": [
      "j-horror",
      "found-footage",
      "supernatural",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.8,
    "douban": 7.2
  },
  {
    "id": 60,
    "title": "Dark Water",
    "year": 2002,
    "director": "Hideo Nakata",
    "tags": [
      "j-horror",
      "supernatural",
      "grief",
      "atmospheric"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.7,
    "douban": 6.9
  },
  {
    "id": 61,
    "title": "Shutter",
    "year": 2004,
    "director": "B. Pisanthanakun",
    "tags": [
      "supernatural",
      "psychological",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 1,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 7,
    "douban": null
  },
  {
    "id": 62,
    "title": "Incantation",
    "year": 2022,
    "director": "Kevin Ko",
    "tags": [
      "found-footage",
      "folk",
      "supernatural",
      "religious"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Netflix"
    ],
    "imdb": 6.3,
    "douban": 6.9
  },
  {
    "id": 63,
    "title": "Exhuma",
    "year": 2024,
    "director": "Jang Jae-hyun",
    "tags": [
      "k-horror",
      "folk",
      "supernatural",
      "occult"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.9,
    "douban": 6.7
  },
  {
    "id": 64,
    "title": "Gonjiam: Haunted Asylum",
    "year": 2018,
    "director": "Jung Bum-shik",
    "tags": [
      "k-horror",
      "found-footage",
      "supernatural",
      "isolation"
    ],
    "scare": 4,
    "gore": 1,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.5,
    "douban": 6.3
  },
  {
    "id": 65,
    "title": "Thirst",
    "year": 2009,
    "director": "Park Chan-wook",
    "tags": [
      "k-horror",
      "vampire",
      "body-horror",
      "religious"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 7.1,
    "douban": 7.5
  },
  {
    "id": 66,
    "title": "The Host",
    "year": 2006,
    "director": "Bong Joon-ho",
    "tags": [
      "k-horror",
      "creature",
      "grief"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 2,
    "gem": false,
    "streaming": [],
    "imdb": 7.1,
    "douban": 7.6
  },
  {
    "id": 67,
    "title": "Sleep",
    "year": 2023,
    "director": "Jason Yu",
    "tags": [
      "k-horror",
      "psychological",
      "possession",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.5,
    "douban": 6
  },
  {
    "id": 68,
    "title": "Bedevilled",
    "year": 2010,
    "director": "Jang Cheol-soo",
    "tags": [
      "k-horror",
      "revenge",
      "isolation",
      "gore"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 7.2,
    "douban": 8.6
  },
  {
    "id": 69,
    "title": "The Call",
    "year": 2020,
    "director": "Lee Chung-hyun",
    "tags": [
      "k-horror",
      "psychological",
      "slasher"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Netflix"
    ],
    "imdb": 7.1,
    "douban": 7.6
  },
  {
    "id": 70,
    "title": "The Quiet Family",
    "year": 1998,
    "director": "Kim Jee-woon",
    "tags": [
      "k-horror",
      "isolation"
    ],
    "scare": 2,
    "gore": 3,
    "dread": 2,
    "gem": true,
    "streaming": [],
    "imdb": 7,
    "douban": 7.2
  },
  {
    "id": 71,
    "title": "Cure",
    "year": 1997,
    "director": "Kiyoshi Kurosawa",
    "tags": [
      "j-horror",
      "psychological",
      "slow-burn",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 5,
    "gem": true,
    "streaming": [],
    "imdb": 7.5,
    "douban": 8.2
  },
  {
    "id": 72,
    "title": "Kwaidan",
    "year": 1964,
    "director": "Masaki Kobayashi",
    "tags": [
      "j-horror",
      "folk",
      "supernatural",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 3,
    "gem": true,
    "streaming": [],
    "imdb": 7.9,
    "douban": 8.6
  },
  {
    "id": 73,
    "title": "Onibaba",
    "year": 1964,
    "director": "Kaneto Shindo",
    "tags": [
      "j-horror",
      "folk",
      "atmospheric",
      "isolation"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 7.8,
    "douban": 8.1
  },
  {
    "id": 74,
    "title": "House",
    "year": 1977,
    "director": "Nobuhiko Obayashi",
    "tags": [
      "j-horror",
      "supernatural",
      "witch"
    ],
    "scare": 2,
    "gore": 3,
    "dread": 2,
    "gem": true,
    "streaming": [],
    "imdb": 7.2,
    "douban": 7.5
  },
  {
    "id": 75,
    "title": "One Cut of the Dead",
    "year": 2017,
    "director": "Shinichiro Ueda",
    "tags": [
      "j-horror",
      "zombie",
      "found-footage"
    ],
    "scare": 1,
    "gore": 2,
    "dread": 1,
    "gem": true,
    "streaming": [],
    "imdb": 7.6,
    "douban": 8.2
  },
  {
    "id": 76,
    "title": "Tetsuo: The Iron Man",
    "year": 1989,
    "director": "Shinya Tsukamoto",
    "tags": [
      "j-horror",
      "body-horror",
      "gore"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.9,
    "douban": 7.2
  },
  {
    "id": 77,
    "title": "Rigor Mortis",
    "year": 2013,
    "director": "Juno Mak",
    "tags": [
      "hk-horror",
      "vampire",
      "supernatural",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.3,
    "douban": 8
  },
  {
    "id": 78,
    "title": "Mr. Vampire",
    "year": 1985,
    "director": "Ricky Lau",
    "tags": [
      "hk-horror",
      "vampire",
      "supernatural",
      "zombie"
    ],
    "scare": 2,
    "gore": 2,
    "dread": 1,
    "gem": true,
    "streaming": [],
    "imdb": 7.2,
    "douban": 8.5
  },
  {
    "id": 79,
    "title": "Out of the Dark",
    "year": 1995,
    "director": "Jeffrey Lau",
    "tags": [
      "hk-horror",
      "supernatural",
      "possession"
    ],
    "scare": 2,
    "gore": 2,
    "dread": 2,
    "gem": true,
    "streaming": [],
    "imdb": 6.8,
    "douban": 8.1
  },
  {
    "id": 80,
    "title": "Double Vision",
    "year": 2002,
    "director": "Chen Kuo-fu",
    "tags": [
      "hk-horror",
      "cult",
      "religious",
      "psychological"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.4,
    "douban": 7.7
  },
  {
    "id": 81,
    "title": "The Eye",
    "year": 2002,
    "director": "Pang Brothers",
    "tags": [
      "hk-horror",
      "supernatural",
      "psychological"
    ],
    "scare": 4,
    "gore": 1,
    "dread": 4,
    "gem": false,
    "streaming": [],
    "imdb": 6.6,
    "douban": 7.3
  },
  {
    "id": 82,
    "title": "Dumplings",
    "year": 2004,
    "director": "Fruit Chan",
    "tags": [
      "hk-horror",
      "body-horror",
      "psychological"
    ],
    "scare": 2,
    "gore": 3,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.7,
    "douban": 6.8
  },
  {
    "id": 83,
    "title": "Detention",
    "year": 2019,
    "director": "John Hsu",
    "tags": [
      "hk-horror",
      "supernatural",
      "psychological",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.6,
    "douban": null
  },
  {
    "id": 84,
    "title": "The Sadness",
    "year": 2021,
    "director": "Rob Jabbaz",
    "tags": [
      "hk-horror",
      "zombie",
      "gore"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 3,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.5,
    "douban": null
  },
  {
    "id": 85,
    "title": "The Medium",
    "year": 2021,
    "director": "Banjong Pisanthanakun",
    "tags": [
      "folk",
      "found-footage",
      "possession",
      "supernatural"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 5,
    "gem": false,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.5,
    "douban": 6.5
  },
  {
    "id": 86,
    "title": "Satan's Slaves",
    "year": 2017,
    "director": "Joko Anwar",
    "tags": [
      "supernatural",
      "religious",
      "possession",
      "atmospheric"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.5,
    "douban": 6.2
  },
  {
    "id": 87,
    "title": "Impetigore",
    "year": 2019,
    "director": "Joko Anwar",
    "tags": [
      "folk",
      "supernatural",
      "isolation"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.6,
    "douban": null
  },
  {
    "id": 88,
    "title": "Bulbbul",
    "year": 2020,
    "director": "Anvita Dutt",
    "tags": [
      "folk",
      "supernatural",
      "revenge",
      "atmospheric"
    ],
    "scare": 2,
    "gore": 2,
    "dread": 3,
    "gem": true,
    "streaming": [
      "Netflix"
    ],
    "imdb": 6.6,
    "douban": null
  },
  {
    "id": 89,
    "title": "Stree",
    "year": 2018,
    "director": "Amar Kaushik",
    "tags": [
      "folk",
      "supernatural"
    ],
    "scare": 2,
    "gore": 1,
    "dread": 2,
    "gem": false,
    "streaming": [],
    "imdb": 7.5,
    "douban": 6.2
  },
  {
    "id": 90,
    "title": "Under the Shadow",
    "year": 2016,
    "director": "Babak Anvari",
    "tags": [
      "supernatural",
      "psychological",
      "isolation",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.8,
    "douban": 6.4
  },
  {
    "id": 91,
    "title": "A Girl Walks Home Alone at Night",
    "year": 2014,
    "director": "Ana Lily Amirpour",
    "tags": [
      "vampire",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 2,
    "gore": 2,
    "dread": 3,
    "gem": true,
    "streaming": [],
    "imdb": 6.9,
    "douban": 6.8
  },
  {
    "id": 92,
    "title": "Terrified",
    "year": 2017,
    "director": "Demián Rugna",
    "tags": [
      "supernatural",
      "atmospheric"
    ],
    "scare": 5,
    "gore": 3,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.5,
    "douban": null
  },
  {
    "id": 93,
    "title": "When Evil Lurks",
    "year": 2023,
    "director": "Demián Rugna",
    "tags": [
      "possession",
      "gore",
      "folk"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.9,
    "douban": null
  },
  {
    "id": 94,
    "title": "Tigers Are Not Afraid",
    "year": 2017,
    "director": "Issa López",
    "tags": [
      "supernatural",
      "grief",
      "atmospheric"
    ],
    "scare": 2,
    "gore": 2,
    "dread": 3,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.9,
    "douban": null
  },
  {
    "id": 95,
    "title": "Possession",
    "year": 1981,
    "director": "Andrzej Żuławski",
    "tags": [
      "psychological",
      "body-horror",
      "cult",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 5,
    "gem": true,
    "streaming": [],
    "imdb": 7.2,
    "douban": 8
  },
  {
    "id": 96,
    "title": "Don't Look Now",
    "year": 1973,
    "director": "Nicolas Roeg",
    "tags": [
      "psychological",
      "grief",
      "slow-burn",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [],
    "imdb": 7.1,
    "douban": 7.2
  },
  {
    "id": 97,
    "title": "Eyes Without a Face",
    "year": 1960,
    "director": "Georges Franju",
    "tags": [
      "body-horror",
      "psychological",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 2,
    "gore": 2,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 7.6,
    "douban": 7.5
  },
  {
    "id": 98,
    "title": "Let the Right One In",
    "year": 2008,
    "director": "Tomas Alfredson",
    "tags": [
      "vampire",
      "slow-burn",
      "atmospheric",
      "grief"
    ],
    "scare": 2,
    "gore": 3,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 7.8,
    "douban": 7.6
  },
  {
    "id": 99,
    "title": "Martyrs",
    "year": 2008,
    "director": "Pascal Laugier",
    "tags": [
      "gore",
      "psychological",
      "cult",
      "revenge"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 5,
    "gem": true,
    "streaming": [],
    "imdb": 7,
    "douban": 6.7
  },
  {
    "id": 100,
    "title": "Inside",
    "year": 2007,
    "director": "Bustillo & Maury",
    "tags": [
      "gore",
      "slasher",
      "isolation"
    ],
    "scare": 4,
    "gore": 5,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.7,
    "douban": 6.4
  },
  {
    "id": 101,
    "title": "Deep Red",
    "year": 1975,
    "director": "Dario Argento",
    "tags": [
      "giallo",
      "slasher",
      "psychological"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 3,
    "gem": true,
    "streaming": [],
    "imdb": 7.5,
    "douban": 7.7
  },
  {
    "id": 102,
    "title": "The Beyond",
    "year": 1981,
    "director": "Lucio Fulci",
    "tags": [
      "supernatural",
      "gore",
      "cosmic",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 5,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.5,
    "douban": null
  },
  {
    "id": 103,
    "title": "Kill List",
    "year": 2011,
    "director": "Ben Wheatley",
    "tags": [
      "cult",
      "folk",
      "psychological",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.3,
    "douban": null
  },
  {
    "id": 104,
    "title": "The Devil's Backbone",
    "year": 2001,
    "director": "Guillermo del Toro",
    "tags": [
      "supernatural",
      "grief",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 7.3,
    "douban": 7.2
  },
  {
    "id": 105,
    "title": "Goodnight Mommy",
    "year": 2014,
    "director": "Franz & Fiala",
    "tags": [
      "psychological",
      "isolation",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.7,
    "douban": null
  },
  {
    "id": 106,
    "title": "Speak No Evil",
    "year": 2022,
    "director": "Christian Tafdrup",
    "tags": [
      "psychological",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.7,
    "douban": 5.9
  },
  {
    "id": 107,
    "title": "Carrie",
    "year": 1976,
    "director": "Brian De Palma",
    "tags": [
      "psychological",
      "supernatural",
      "religious"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 7.4,
    "douban": 7.6
  },
  {
    "id": 108,
    "title": "The Omen",
    "year": 1976,
    "director": "Richard Donner",
    "tags": [
      "religious",
      "occult",
      "supernatural"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 7.5,
    "douban": 7.4
  },
  {
    "id": 109,
    "title": "Poltergeist",
    "year": 1982,
    "director": "Tobe Hooper",
    "tags": [
      "supernatural",
      "possession"
    ],
    "scare": 3,
    "gore": 2,
    "dread": 2,
    "gem": false,
    "streaming": [],
    "imdb": 7.3,
    "douban": 6.8
  },
  {
    "id": 110,
    "title": "A Nightmare on Elm Street",
    "year": 1984,
    "director": "Wes Craven",
    "tags": [
      "slasher",
      "supernatural"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 7.4,
    "douban": 7.5
  },
  {
    "id": 111,
    "title": "Hellraiser",
    "year": 1987,
    "director": "Clive Barker",
    "tags": [
      "body-horror",
      "gore",
      "supernatural",
      "occult"
    ],
    "scare": 3,
    "gore": 5,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 6.9,
    "douban": null
  },
  {
    "id": 112,
    "title": "The Fly",
    "year": 1986,
    "director": "David Cronenberg",
    "tags": [
      "body-horror",
      "gore"
    ],
    "scare": 3,
    "gore": 5,
    "dread": 4,
    "gem": false,
    "streaming": [],
    "imdb": 7.6,
    "douban": 7.5
  },
  {
    "id": 113,
    "title": "Re-Animator",
    "year": 1985,
    "director": "Stuart Gordon",
    "tags": [
      "body-horror",
      "gore",
      "zombie"
    ],
    "scare": 2,
    "gore": 5,
    "dread": 2,
    "gem": true,
    "streaming": [],
    "imdb": 7.1,
    "douban": 7.4
  },
  {
    "id": 114,
    "title": "Evil Dead II",
    "year": 1987,
    "director": "Sam Raimi",
    "tags": [
      "possession",
      "gore",
      "supernatural"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 2,
    "gem": false,
    "streaming": [],
    "imdb": 7.6,
    "douban": 7.3
  },
  {
    "id": 115,
    "title": "Candyman",
    "year": 1992,
    "director": "Bernard Rose",
    "tags": [
      "supernatural",
      "slasher",
      "psychological"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 6.8,
    "douban": 6.7
  },
  {
    "id": 116,
    "title": "Scream",
    "year": 1996,
    "director": "Wes Craven",
    "tags": [
      "slasher"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 2,
    "gem": false,
    "streaming": [],
    "imdb": 7.4,
    "douban": 7.2
  },
  {
    "id": 117,
    "title": "The Others",
    "year": 2001,
    "director": "Alejandro Amenábar",
    "tags": [
      "supernatural",
      "psychological",
      "slow-burn",
      "atmospheric"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 4,
    "gem": false,
    "streaming": [],
    "imdb": 7.6,
    "douban": 8.2
  },
  {
    "id": 118,
    "title": "28 Days Later",
    "year": 2002,
    "director": "Danny Boyle",
    "tags": [
      "zombie",
      "isolation"
    ],
    "scare": 4,
    "gore": 4,
    "dread": 4,
    "gem": false,
    "streaming": [],
    "imdb": 7.5,
    "douban": 7.2
  },
  {
    "id": 119,
    "title": "Session 9",
    "year": 2001,
    "director": "Brad Anderson",
    "tags": [
      "psychological",
      "atmospheric",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [],
    "imdb": 6.3,
    "douban": 6.5
  },
  {
    "id": 120,
    "title": "Sinister",
    "year": 2012,
    "director": "Scott Derrickson",
    "tags": [
      "supernatural",
      "occult",
      "found-footage"
    ],
    "scare": 5,
    "gore": 3,
    "dread": 4,
    "gem": false,
    "streaming": [],
    "imdb": 6.8,
    "douban": 6.9
  },
  {
    "id": 121,
    "title": "Insidious",
    "year": 2010,
    "director": "James Wan",
    "tags": [
      "supernatural",
      "possession"
    ],
    "scare": 4,
    "gore": 1,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 6.8,
    "douban": 7.9
  },
  {
    "id": 122,
    "title": "The House of the Devil",
    "year": 2009,
    "director": "Ti West",
    "tags": [
      "occult",
      "cult",
      "slow-burn",
      "isolation"
    ],
    "scare": 3,
    "gore": 3,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.3,
    "douban": 5.4
  },
  {
    "id": 123,
    "title": "Lake Mungo",
    "year": 2008,
    "director": "Joel Anderson",
    "tags": [
      "found-footage",
      "grief",
      "supernatural",
      "slow-burn"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 5,
    "gem": true,
    "streaming": [],
    "imdb": 6.2,
    "douban": 6.8
  },
  {
    "id": 124,
    "title": "Paranormal Activity",
    "year": 2007,
    "director": "Oren Peli",
    "tags": [
      "found-footage",
      "supernatural",
      "possession"
    ],
    "scare": 4,
    "gore": 1,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 6.3,
    "douban": null
  },
  {
    "id": 125,
    "title": "The Cabin in the Woods",
    "year": 2011,
    "director": "Drew Goddard",
    "tags": [
      "slasher",
      "zombie",
      "cosmic"
    ],
    "scare": 3,
    "gore": 4,
    "dread": 1,
    "gem": false,
    "streaming": [],
    "imdb": 7,
    "douban": 7.6
  },
  {
    "id": 126,
    "title": "The Autopsy of Jane Doe",
    "year": 2016,
    "director": "André Øvredal",
    "tags": [
      "supernatural",
      "witch",
      "isolation"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 4,
    "gem": false,
    "streaming": [],
    "imdb": 6.8,
    "douban": 7.6
  },
  {
    "id": 127,
    "title": "Hush",
    "year": 2016,
    "director": "Mike Flanagan",
    "tags": [
      "slasher",
      "isolation"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 3,
    "gem": false,
    "streaming": [
      "Netflix"
    ],
    "imdb": 6.6,
    "douban": 6.3
  },
  {
    "id": 128,
    "title": "Creep",
    "year": 2014,
    "director": "Patrick Brice",
    "tags": [
      "found-footage",
      "psychological",
      "slasher"
    ],
    "scare": 3,
    "gore": 1,
    "dread": 4,
    "gem": true,
    "streaming": [
      "Netflix"
    ],
    "imdb": 6.3,
    "douban": 6.3
  },
  {
    "id": 129,
    "title": "It",
    "year": 2017,
    "director": "Andy Muschietti",
    "tags": [
      "creature",
      "supernatural"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 2,
    "gem": false,
    "streaming": [],
    "imdb": 7.3,
    "douban": 7.5
  },
  {
    "id": 130,
    "title": "Us",
    "year": 2019,
    "director": "Jordan Peele",
    "tags": [
      "psychological",
      "slasher"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 6.8,
    "douban": 6.4
  },
  {
    "id": 131,
    "title": "Hell House LLC",
    "year": 2015,
    "director": "Stephen Cognetti",
    "tags": [
      "found-footage",
      "supernatural",
      "dolls"
    ],
    "scare": 4,
    "gore": 1,
    "dread": 4,
    "gem": true,
    "streaming": [],
    "imdb": 6.4,
    "douban": 6.6
  },
  {
    "id": 132,
    "title": "His House",
    "year": 2020,
    "director": "Remi Weekes",
    "tags": [
      "supernatural",
      "grief",
      "psychological"
    ],
    "scare": 4,
    "gore": 2,
    "dread": 4,
    "gem": false,
    "streaming": [
      "Netflix"
    ],
    "imdb": 6.4,
    "douban": 6
  },
  {
    "id": 133,
    "title": "The Dark and the Wicked",
    "year": 2020,
    "director": "Bryan Bertino",
    "tags": [
      "possession",
      "supernatural",
      "isolation",
      "grief"
    ],
    "scare": 4,
    "gore": 3,
    "dread": 5,
    "gem": true,
    "streaming": [
      "Shudder"
    ],
    "imdb": 6.1,
    "douban": 5.6
  },
  {
    "id": 134,
    "title": "Smile",
    "year": 2022,
    "director": "Parker Finn",
    "tags": [
      "psychological",
      "supernatural"
    ],
    "scare": 5,
    "gore": 3,
    "dread": 3,
    "gem": false,
    "streaming": [],
    "imdb": 6.5,
    "douban": 6.4
  },
  {
    "id": 135,
    "title": "M3GAN",
    "year": 2022,
    "director": "Gerard Johnstone",
    "tags": [
      "dolls",
      "slasher"
    ],
    "scare": 2,
    "gore": 2,
    "dread": 1,
    "gem": false,
    "streaming": [],
    "imdb": 6.3,
    "douban": 6
  }
];
